[package]
authors = ["Bruno Tavares <connect+github@bltavares.com>"]
name = "pickpocket"
version = "0.1.0"

[dependencies]
bincode = "0.8.0"
chrono = "0.3.1"
flate2 = "0.2.19"
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
rustc-serialize = "0.3.24"
