[package]
authors = ["Bruno Tavares <connect+github@bltavares.com>"]
name = "pickpocket"
version = "0.1.0"

[dependencies]
bincode = "0.6.0"
chrono = "0.3.0"
flate2 = "0.2.14"
hyper = "0.10.5"
hyper-native-tls = "0.2.2"
rustc-serialize = "0.3.16"
